env:
  - GO111MODULE=on
  - CGO_ENABLED=0 # For the sqlite dependency

before:
  hooks:
    - make build-ui

builds:
  - binary: gullak.bin
    id: gullak
    main: ./
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X "main.buildString={{ .Tag }} ({{ .ShortCommit }} {{ .Date }})"

archives:
  - format: tar.gz
    files:
      - README.md
      - LICENSE
      - config.sample.toml

dockers:
  - id: gullak-amd64
    use: buildx
    goos: linux
    goarch: amd64
    ids:
      - gullak
    image_templates:
      - "ghcr.io/mr-karan/gullak:{{ .Tag }}-amd64"
      - "ghcr.io/mr-karan/gullak:latest-amd64"
    skip_push: false
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.description=Gullak - Personal expense tracker"
      - "--label=org.opencontainers.image.url=https://github.com/mr-karan/gullak"
      - "--label=org.opencontainers.image.source=https://github.com/mr-karan/gullak"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    extra_files:
      - config.sample.toml

  - id: gullak-arm64
    use: buildx
    goos: linux
    goarch: arm64
    ids:
      - gullak
    image_templates:
      - "ghcr.io/mr-karan/gullak:{{ .Tag }}-arm64"
      - "ghcr.io/mr-karan/gullak:latest-arm64"
    skip_push: false
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.description=Gullak - Personal expense tracker"
      - "--label=org.opencontainers.image.url=https://github.com/mr-karan/gullak"
      - "--label=org.opencontainers.image.source=https://github.com/mr-karan/gullak"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    extra_files:
      - config.sample.toml

docker_manifests:
  - name_template: "ghcr.io/mr-karan/gullak:{{ .Tag }}"
    image_templates:
      - "ghcr.io/mr-karan/gullak:{{ .Tag }}-amd64"
      - "ghcr.io/mr-karan/gullak:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/mr-karan/gullak:latest"
    image_templates:
      - "ghcr.io/mr-karan/gullak:latest-amd64"
      - "ghcr.io/mr-karan/gullak:latest-arm64"
