[app]
debug = true
currency = "INR"
db_path = "./expenses.db"

[http]
address = ":3333"
timeout = "30s"

[openai]
token = "redacted"
base_url = "https://api.openai.com/v1"
model = "gpt-4o-mini"
timeout = "10s"

[telegram]
token = ""
